<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P11-AS-CHSSXC2" name="com.altisource.MPT_ReoTest.MptReoTests" tests="1" failures="0" timestamp="26 Jan 2018 12:46:13 GMT" time="63.710" errors="1">
  <testcase name="runMptReoPTC_A_RecordFirstCashTest" time="63.710" classname="com.altisource.MPT_ReoTest.MptReoTests">
    <error type="java.lang.AssertionError" message="The Assertion for No of Milestones for the ProductType got failed. expected [97] but found [98]">
      <![CDATA[java.lang.AssertionError: The Assertion for No of Milestones for the ProductType got failed. expected [97] but found [98]
	at com.data.altisource.framework.SoftAsserts.fail(SoftAsserts.java:82)
	at com.data.altisource.framework.SoftAsserts.failNotEquals(SoftAsserts.java:482)
	at com.data.altisource.framework.SoftAsserts.assertEquals(SoftAsserts.java:111)
	at com.data.altisource.framework.SoftAsserts.assertEquals(SoftAsserts.java:358)
	at com.data.altisource.library.MptREOTestLibrary.reoAllFileInsertQueries(MptREOTestLibrary.java:202)
	at com.data.altisource.library.MptREOTestLibrary.reoAllDataCreation(MptREOTestLibrary.java:213)
	at com.altisource.MPT_ReoTest.MptReoTests.runMptReoPTC_A_RecordFirstCashTest(MptReoTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runMptReoPTC_A_RecordFirstCashTest -->
</testsuite> <!-- com.altisource.MPT_ReoTest.MptReoTests -->
